### ISSUE TITLE
Crear primeros componentes reutilizables (botones, formularios).

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#10]

**Comment by JoelGonzalez08** [comment]
Con el fin de hacer una UI más intuitiva y amigable para el usuario, propongo estos botones principales para usarse entre los diferentes componentes que componen a nuestro servicio. A medida que vaya surgiendo la necesidad se irán agregando, quitando o modificando. Si gustan, pueden visitar uiverse.io que fue la página donde encontré estos botones y barras de búsqueda.

![Image](https://github.com/user-attachments/assets/bc0312b0-d3b3-45de-a775-6c1914b8e01c)

**Comment by jairoserrano** [comment]
adelante
