### ISSUE TITLE
Implementar la interfaz básica de usuario para la selección de materias

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#11]

**Comment by JesusLomac** [comment]
Despues de ver unos cuantos videos en Youtube, fui capaz de crear una interfaz simple para la seleccion de materias. Ademas logre hacer una pequeña prueba con la opcion de prototipos que ofrece Figma.

Aca los resultados:
![Image](https://github.com/user-attachments/assets/7c99d8b7-31be-4b98-bdb1-6647512589dc)
https://github.com/user-attachments/assets/c22d4066-085d-457c-8eae-689e425290a8

**Comment by Maykol0721** [comment]
![Homepage - ClassMesh-UTB (1)](https://github.com/user-attachments/assets/395ade6a-aacb-4162-91d2-35276525e47e)


https://github.com/user-attachments/assets/e0046da6-5532-4bd0-8809-1ce2914a1de6


Mediante tutoriales y haciendo uso de distintos recursos, instalando html y css en VS Code, probando con la consola de Google Chrome, además de apoyarme con la herramienta Uiverse, aprendí a desarrollar un homepage para ClassMesh-UTB con un enfoque en la experiencia de usuario (UX) y un diseño limpio, funcional e intuitivo. Durante el proceso, integré botones interactivos, como "Iniciar sesión con Microsoft 365", asegurándome de que cada uno tuviera transiciones suaves mediante CSS, con el fin de demostrar una mayor interactuar con la interfaz. Estas transiciones mejoran la retroalimentación visual, haciendo que los usuarios se sientan más conectados con la aplicación al percibir cambios visuales sutiles cuando pasan el cursor sobre los botones o hacen clic en ellos.

También logré mantener una jerarquía visual clara, donde los elementos principales, como el mensaje central y el botón de inicio de sesión, están posicionados estratégicamente para captar la atención del usuario de manera inmediata. El uso de un calendario de ejemplo también añade valor a la comunicación visual, mostrando de forma simple el propósito de la herramienta.

**Comment by JoelGonzalez08** [comment]
En base a los wireframes diseñados y a varias ideas comentadas por nuestro principal medio de comunicación (Whatsapp), elaboré esta base para lo que puede ser la página de inicio de los usuarios cuando inicien sesión. Aquí se presentarán todos los horarios que tengan guardados previamente y en futuras actualizaciones se integrará la opción de agregar horarios para así llevarlos a la interfaz de generación de horarios.  Esta base fue hecha en flutter para así empezar a poner en práctica lo aprendido en el proceso.
https://github.com/user-attachments/assets/6e613886-e1ad-4308-bb82-076e596f8b79

**Comment by jairoserrano** [comment]
adelante.
