### ISSUE TITLE
Investigar y seleccionar herramientas de web scrapping para extraer datos de banner

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#12]
Apartir de las tecnologías en lenguaje python, harás o diseñarás las primeras funciones para la extracción de datos por xpath, HTML. Y realizar ejemplares con sitios con autenticación

- Una vez logrado, Extraer los primeros 5 cursos de banner en general

**Comment by AlviAng12** [comment]
# Se usarán tecnologias de webscrapping y manejo de solicitudes HTTP 

Librerias:

- **Selenium**

[![imagen_2024-09-16_102720073](https://github.com/user-attachments/assets/cd23de57-ee17-46b5-99a2-3393cda1af6c)](https://www.selenium.dev)

- **Requests**
[![imagen_2024-09-16_102946125](https://github.com/user-attachments/assets/ff1bc449-5304-4acf-82c6-70defb81067c)](https://pypi.org/project/requests/)
