### ISSUE TITLE
Implementar la lógica para almacenar datos en la base de datos.

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#15]

**Comment by sebasssruizz** [comment]
Se tomaron solamente los datos necesarios de la primera extracción de datos, datos como el nombre del programa, el profesor, los horarios, entre otros.
![Image](https://github.com/user-attachments/assets/f9342c7b-cc53-4bf4-a8aa-53544d2d4f79)

**Comment by jairoserrano** [comment]
Por revisar en código
