### ISSUE TITLE
Implementar feedback visual en la UI (loaders, mensajes de error).

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#18]

**Comment by Maykol0721** [comment]
https://github.com/user-attachments/assets/3a03e198-2e86-419a-b62c-90a78708de39

Muestra un mensaje de error en dado caso el usuario se equivoque al hacer la búsqueda de un horario en específico.

**Comment by JesusLomac** [comment]
Concepto para un mensaje de error al comparar horarios:
https://github.com/user-attachments/assets/6ef520fb-461f-475f-bb1c-38fe43dc8d04

**Comment by jairoserrano** [comment]
adelante
