### ISSUE TITLE
Mejorar la interfaz para hacer la selección de materias más intuitiva.

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#19]

**Comment by Maykol0721** [comment]
![Image](https://github.com/user-attachments/assets/e1991dbe-757e-4441-96bf-1f36b9a75e43)

Tomando como base lo hecho por mi compañero Jesús, modifique y mejore la pagina mediante una API, con el fin de hacerla mas intuitiva al seleccionar las materias, previo a la generación de horarios.

**Comment by JoelGonzalez08** [comment]
Teniendo definidas las pantallas iniciales, hice el proceso de enlazar una pantalla con otra. Aquí se puede ver un video demostrativo de cómo va avanzando el apartado visual de la parte web de nuestro servicio. Ya se encuentran incluidos algunos mensajes de error y confirmación para la selección de materias y eliminación/búsqueda de horarios.

Nota: Para la selección de las materias y facultades de la última pantalla se usó una api de prueba con datos básicos para verificar que todo funcione. En futuras semanas se estará actualizando esto y se diseñará la interfaz de cómo esas materias se verán en la generación de horarios.
https://github.com/user-attachments/assets/a622204c-7a0e-4df3-ab15-82507c95100b

**Comment by jairoserrano** [comment]
Adelante
