### ISSUE TITLE
Taller de Flutter

### ISSUE THREAD

**Issue by sebasssruizz** [ISCOUTB/DG-ClassMesh-UTB#5]
hola

**Comment by JoelGonzalez08** [comment]
Hola. Les envío una serie de videos/cursos que nos podrían servir para empezar a conocer el entorno de flutter y cómo podemos trabajar con él. Cualquier duda o retroalimentación podemos ir comentándolo y socializando el progreso que vamos teniendo al respecto.

Cursos de Udemy:  
- https://www.udemy.com/course/flutter-nivel-facil-aprende-a-desarrollar-tu-primera-app/
- https://www.udemy.com/course/developing-app-using-flutter/

Videos/Playlist de Youtube:
- https://youtu.be/7N-wDxe18PA?si=VFgUs9kfjN3zIfvH
- https://youtu.be/OIlhCrBp-uw?si=dLtaTJ35bMmRTHka
- https://www.youtube.com/watch?v=CoPnDnJjVSk&list=PLl_hIu4u7P677H9f6zPOHiOz2izkvQq2E

**Comment by JoelGonzalez08** [comment]
Luego de ver los videos y los cursos, logré comprender muchos conceptos de cómo funciona flutter y aprender acerca de su entorno. A continuación adjunto captura de algunas pruebas al configurar flutter con vs code, al igual que probar con los diferentes simuladores que ofrece.

![Captura de pantalla 2024-09-09 021104](https://github.com/user-attachments/assets/f5a98fca-d9cc-4994-9a56-2338ed0e5b8b)

**Comment by JesusLomac** [comment]
Igualmente despues de analizar los videos enviados por mi compañero pude darle forma a una aplicacion sencilla, asi mismo logre entender los conceptos basicos de flutter y su entorno.

Aca adjunto una imagen:
[](url)![Image](https://github.com/user-attachments/assets/f8f44d04-fe4b-44ba-ab7f-5ad3168ab025)

**Comment by jairoserrano** [comment]
ok adelante
