### ISSUE TITLE
Definir Wireframes de la aplicación

### ISSUE THREAD

**Issue by sebasssruizz** [ISCOUTB/DG-ClassMesh-UTB#7]

**Comment by Maykol0721** [comment]
![Image](https://github.com/user-attachments/assets/a1313911-43a3-453f-befe-3199fc67ea9d)

Esta imagen es un adelante con respecto a las proyecciones que tenemos para nuestra aplicación.
Trabajé en los wireframes iniciales de la homepage del proyecto con ayuda de diversas páginas web, principalmente Visme. Aunque es una versión preliminar, ya nos ofrece una visión clara de cómo organizar la información y diseñar el flujo de navegación. Por eso mismo, subiré la imagen, para que así, de ser necesario se pueda establecer una nueva revisión y sugerir ajustes o mejoras.

**Comment by JoelGonzalez08** [comment]
Diseñé una página de inicio para escoger entre una selección de horarios guardados por el usuario para que pueda navegar entre ellos, editarlos y eliminarlos cuando guste. Aquí se puede ver el comienzo de lo que va a ser la interfaz de los usuarios cuando ya estén autenticados e inicien sesión. Este wireframe fue desarrollado en la plataforme de **visme** y está sujeto a cambios que vayamos comentando.

![Captura de pantalla 2024-09-08 220333](https://github.com/user-attachments/assets/07fe8576-3498-4a6c-b651-4ea6837bd0d1)

**Comment by jairoserrano** [comment]
acordado el wireframe.
