### ISSUE TITLE
FAST API, Principio y configuración basica

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#8]

**Comment by sebasssruizz** [comment]
![Image](https://github.com/user-attachments/assets/cbe91260-866b-4dd0-bc76-16173b501096)

Se corrigieron algunos errores que no permitían instalar Fast Api dentro del entorno virtual, se instaló y se comenzaron a hacer pruebas

**Comment by AlviAng12** [comment]
![imagen_2024-09-16_104325964](https://github.com/user-attachments/assets/4d141a1f-a1b7-4b85-b486-d1f071b7ddfb)

Se empezó a configurar fastAPI con uvicorn para visualizar los url y fomentar las bases para un buen enrutado

**Comment by jairoserrano** [comment]
ok adelante
