### ISSUE TITLE
Estructuración del modelo de datos y modelado relacional

### ISSUE THREAD

**Issue by JoelGonzalez08** [ISCOUTB/DG-ClassMesh-UTB#9]

**Comment by AlviAng12** [comment]
![Diagrama sin título drawio](https://github.com/user-attachments/assets/e922c02e-5957-4f3a-b6a1-ed8778d9b613)


# Diagrama Entidad relacional del prototipo funcional de la Aplicación

Atraves de este podremos realizar los primeros filtros y funciones basicas de nuestro mezclador de horarios

**Comment by jairoserrano** [comment]
adelante. faltó el no relacional.
